<?php

namespace FlexiAPI\Endpoints;

use FlexiAPI\Core\BaseEndpointController;
use FlexiAPI\Utils\Response;
use FlexiAPI\Utils\Validator;

/**
 * UsersController - Auto-generated by FlexiAPI CLI
 * Endpoint: /users
 * Generated on: 2025-10-22 14:16:28
 */
class UsersController extends BaseEndpointController
{
    protected string $tableName = 'users';
    protected array $fillable = ['Name', 'Age', 'Password'];
    protected array $encrypted = ['Password'];
    protected array $hidden = [];

    protected function getValidationRules(): array
    {
        return [
            'Name' => 'required',
            'Age' => 'required',
            'Password' => '',
        ];
    }

    // Add custom methods here
}
